// Generated by Selenium IDE
using OpenQA.Selenium;
using OpenQA.Selenium.Interactions;
using UserFlowTests;
using AwesomeAssertions;

[TestFixture]
public class PickherupTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = DriverExtensions.CreateTestDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
    driver.Dispose();
  }

  private string CaptureState() {
    return (string)((IJavaScriptExecutor)driver).ExecuteScript(@"
      try {
        return JSON.stringify({
          errors: window.__capturedErrors || [],
          textsp: (document.getElementById('textsp')?.innerText || '').substring(0, 2000),
          textspHtml: (document.getElementById('textsp')?.innerHTML || '').substring(0, 3000),
          locStack: Array.isArray(window.locStack) ? JSON.stringify(window.locStack) : typeof window.locStack,
          allActions: Array.from(document.querySelectorAll('[data-action]')).map(e => e.dataset.action + ': ' + (e.innerText || '').substring(0,50)),
          allFnActions: Array.from(document.querySelectorAll('[data-action-fn]')).map(e => e.id)
        });
      } catch(e) { return JSON.stringify({evalError: e.message}); }
    ");
  }

  [Test]
  [Description("Covers the phone->store->second call->pickup route and verifies the pickup branch renders successfully.")]
  public void PickHerUp_PhoneAndStoreProgression_ReachesPickupFlow() {
    driver.Navigate().GoToUrl("http://localhost:8080?seed=20260307");
    driver.Manage().Window.Size = new System.Drawing.Size(1268, 1042);
    driver.SetGameSeed(20260307);
    driver.ClickWhenInteractable(By.CssSelector("pre:nth-child(4)"));
    driver.ClickWhenInteractable(By.Id("start"));
    driver.DismissDisclaimerPopupIfPresent();
    driver.ClickWhenInteractable(By.LinkText("Start the game."));
    System.Threading.Thread.Sleep(3000);

    // Helper: invoke a go() action for a choice found by partial link text
    Action<string> GoLink = (string partialText) => {
      Thread.Sleep(100);
      var result = (string)((IJavaScriptExecutor)driver).ExecuteScript(@"
        var links = Array.from(document.querySelectorAll('[data-action]'));
        var match = links.find(function(el) { return el.innerText.indexOf(arguments[0]) >= 0; });
        if (!match) return JSON.stringify({found:false, textsp: (document.getElementById('textsp')?.innerText || '').substring(0,200)});
        window.go(match.dataset.action);
        var t = (document.getElementById('textsp')?.innerText || '').substring(0, 500);
        return JSON.stringify({found:true, textsp:t, locStack: JSON.stringify(window.locStack), errors: window.__capturedErrors||[]});
      ", partialText);
      var parsed = System.Text.Json.JsonDocument.Parse(result);
      if (!parsed.RootElement.GetProperty("found").GetBoolean())
        throw new Exception("Link not found: " + partialText + " State: " + parsed.RootElement.GetProperty("textsp").GetString());
    };

    // 1. Start phone call
    js.ExecuteScript("window.go('callher');");
    System.Threading.Thread.Sleep(200);

    // 2. Flirt (medium) — need to pass function ref directly
    js.ExecuteScript("window.go(flirt_m);");
    System.Threading.Thread.Sleep(200);

    // 3. Continue back to phone
    GoLink("Continue...");

    // 4. Hang up — "Say See you soon and hang up"
    GoLink("See you soon and hang up.");

    // 5. Pick her up from home screen
    GoLink("Pick her up");
  }
}
