// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using UserFlowTests;

[TestFixture]
public class PickherupTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void pickherup() {
    driver.Navigate().GoToUrl("http://localhost:8080");
    driver.Manage().Window.Size = new System.Drawing.Size(1268, 1042);
    driver.FindElement(By.CssSelector("pre:nth-child(4)")).Click();
    driver.FindElement(By.Id("start")).Click();
    driver.FindElement(By.Id("close-pop-up")).Click();
    driver.FindElement(By.LinkText("Start the game.")).Click();
    driver.FindElement(By.LinkText("Call her on the phone")).Click();
    driver.FindHighestFlirt().Click();
    driver.FindElement(By.LinkText("Continue...")).Click();
    driver.FindHighestFlirt().Click();
    driver.FindElement(By.LinkText("Continue...")).Click();
    driver.FindElement(By.CssSelector("i")).Click();
    driver.FindElement(By.LinkText("Go to the store")).Click();
    driver.FindElement(By.LinkText("A bottle of fancy champagne ($50)")).Click();
    driver.FindElement(By.Id("buy")).Click();
    driver.FindElement(By.LinkText("Continue...")).Click();
    driver.FindElement(By.LinkText("A pair of sexy panties ($30)")).Click();
    driver.FindElement(By.Id("buy")).Click();
    driver.FindElement(By.Id("textsp")).Click();
    driver.FindElement(By.Id("textsp")).Click();
    {
      var element = driver.FindElement(By.Id("textsp"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.FindElement(By.LinkText("Continue...")).Click();
    driver.FindElement(By.LinkText("Nothing")).Click();
    driver.FindElement(By.LinkText("Call her on the phone")).Click();
    driver.FindHighestFlirt().Click();
    driver.FindElement(By.Id("textsp")).Click();
    driver.FindElement(By.LinkText("Continue...")).Click();
    driver.FindHighestFlirt().Click();
    driver.FindElement(By.LinkText("Continue...")).Click();
    driver.FindElement(By.CssSelector("i")).Click();
    driver.FindElement(By.Id("textsp")).Click();
    driver.FindElement(By.LinkText("Pick her up")).Click();
    driver.FindElement(By.Id("leavehm")).Click();
  }
}