// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using UserFlowTests;

[TestFixture]
public class PickherupTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void pickherup() {
    driver.Navigate().GoToUrl("http://localhost:8080?seed=20260307");
    driver.Manage().Window.Size = new System.Drawing.Size(1268, 1042);
    driver.SetGameSeed(20260307);
    driver.ClickWhenInteractable(By.CssSelector("pre:nth-child(4)"));
    driver.ClickWhenInteractable(By.Id("start"));
    driver.ClickWhenInteractable(By.Id("close-pop-up"));
    driver.ClickWhenInteractable(By.LinkText("Start the game."));
    driver.ClickWhenInteractable(By.LinkText("Call her on the phone"));
    driver.ClickWhenInteractable(MelissaBy.Flirt(FlirtLevel.High));
    driver.ClickWhenInteractable(By.LinkText("Continue..."));
    driver.ClickWhenInteractable(MelissaBy.Flirt(FlirtLevel.High));
    driver.ClickWhenInteractable(By.LinkText("Continue..."));
    driver.ClickWhenInteractable(By.CssSelector("i"));
    driver.ClickWhenInteractable(By.LinkText("Go to the store"));
    driver.ClickWhenInteractable(By.LinkText("A bottle of fancy champagne ($50)"));
    driver.ClickWhenInteractable(By.Id("buy"));
    driver.ClickWhenInteractable(By.LinkText("Continue..."));
    driver.ClickWhenInteractable(By.LinkText("A pair of sexy panties ($30)"));
    driver.ClickWhenInteractable(By.Id("buy"));
    driver.ClickWhenInteractable(By.Id("textsp"));
    driver.ClickWhenInteractable(By.Id("textsp"));
    {
      var element = driver.FindElement(By.Id("textsp"));
      Actions builder = new Actions(driver);
      builder.DoubleClick(element).Perform();
    }
    driver.ClickWhenInteractable(By.LinkText("Continue..."));
    driver.ClickWhenInteractable(By.LinkText("Nothing"));
    driver.ClickWhenInteractable(By.LinkText("Call her on the phone"));
    driver.ClickWhenInteractable(MelissaBy.Flirt(FlirtLevel.High));
    driver.ClickWhenInteractable(By.Id("textsp"));
    driver.ClickWhenInteractable(By.LinkText("Continue..."));
    driver.ClickWhenInteractable(MelissaBy.Flirt(FlirtLevel.High));
    driver.ClickWhenInteractable(By.LinkText("Continue..."));
    driver.ClickWhenInteractable(By.CssSelector("i"));
    driver.ClickWhenInteractable(By.Id("textsp"));
    driver.ClickWhenInteractable(By.LinkText("Pick her up"));
    driver.ClickWhenInteractable(By.Id("leavehm"));
  }
}